###################
#### Image for BUILDING
###################
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

# copy the csproject into the container LAYER 1
RUN mkdir SynopticumModel \
                  SynopticumWebAPI \
                  SynopticumCore \
                  SynopticumDAL \
                  SynopticumTestsDbSeed

COPY SynopticumModel/*.csproj SynopticumModel/
COPY SynopticumWebAPI/*.csproj SynopticumWebAPI/
COPY SynopticumCore/*.csproj SynopticumCore/
COPY SynopticumDAL/*.csproj SynopticumDAL/
COPY SynopticumTestsDbSeed/*.csproj SynopticumTestsDbSeed/

# pull the nuget packages
RUN dotnet restore SynopticumWebAPI/SynopticumWebAPI.csproj

# copy the rest of the application sources
COPY . .

# build the application
RUN dotnet build SynopticumWebAPI/SynopticumWebAPI.csproj -c Release -o /app



###################
#### Image for RUNNING
###################
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime

WORKDIR /app

# Copy the built application from the build stage
COPY --from=build /app .

# Expose the application port
EXPOSE 8081

# Set the entry point to run the application
ENTRYPOINT ["dotnet", "SynopticumWebAPI.dll", "--urls", "http://*:8081"]

