###################
#### Image for BUILDING
###################
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

# copy the csproject into the container LAYER 1
COPY backend.csproj backend.csproj

# pull the nuget packages
RUN dotnet restore backend.csproj

# copy the rest of the application sources
COPY . .

# build the application
RUN dotnet build backend.csproj -c Release -o /app



###################
#### Image for RUNNING
###################
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime

WORKDIR /app

# Copy the built application from the build stage
COPY --from=build /app .

# Expose the application port
EXPOSE 8081

# Set the entry point to run the application
ENTRYPOINT ["dotnet", "backend.dll", "--urls", "http://*:8081"]

